#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

bspc monitor -d I II III IV V
bspc monitor eDP-1-1 -d I II III IV V
bspc monitor HDMI-0 -d VI VII VIII XI
bspc monitor DP-0 -d VI VII VIII IX X

bspc config border_width        5
bspc config window_gap          32
bspc config top_padding 	      30
bspc config border_radius 	    12

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc config focused_border_color "#191724"
bspc config normal_border_color "#232136"

# ---> Autostart process

exec xfce4-power-manager &
feh --bg-fill ~/.config/backgrounds/BG-03.jpg &
sh ~/.config/polybar/launch.sh &
sh ~/.config/bspwm/scripts/screenLayout.sh
picom --config ~/.config/picom/picom.conf &
