classic: false
blocks:
  - permission
  - user
  - group
  - size
  - date
  - name

color:
  when: auto
  theme: ~/.config/lsd/themes/theme.yaml

icons:
  when: auto
  theme: fancy
  separator: " "

indicators: false
layout: grid
recursion:
permission: rwx

sorting:
  column: name
  reverse: false
  dir-grouping: none

no-symlink: false
total-size: false
hyperlink: never
symlink-arrow: ⇒
header: false
